[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 2

[scrolling]
history = 20000

[terminal.shell]
args = ["-fp", "qwe"]
program = "/usr/bin/login"

[window]
opacity = 0.8
option_as_alt = "OnlyLeft"

[keyboard]
bindings = [
    # font size
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },

    # ctrl-H tmux fix
    # { key = "H", mods = "Control", chars = "\u0008" }
]

[terminal]
